sudo: false

language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6

    packages:
      - libstdc++-7-dev
      - clang-6.0

install:
  - "export CXX=clang++-6.0 || true"

before_script:
  - mkdir build
  - cd build
  - cmake -D TESTS=ON ..

script:
  - make VERBOSE=1
  - ./tests
