sudo: false

language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6

    packages:
      - libstdc++-7-dev
      - clang-3.6

install:
  - "export CXX=clang++-3.6 || true"

before_script:
  - mkdir build
  - cd build
  - cmake -D TESTS=ON ..

script:
  - make
  - ./tests
